name: idlebattle
description: An idle game to battle enemies
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.17.6 <3.0.0'

dependencies:
  get_it: ^7.2.0
  dafluta: ^4.1.0
  just_audio: ^0.9.28
  share_plus: ^4.0.10+1
  url_strategy: ^0.2.0
  json_annotation: ^4.6.0
  web_socket_channel: ^2.2.0
  shared_preferences: ^2.0.15
  
  firebase_core: ^1.21.0
  firebase_auth: ^3.6.4

  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter 

dev_dependencies:
  dalocale: ^2.4.2
  daunused: ^1.3.0
  dapublock: ^1.0.1
  build_runner: ^2.2.0
  flutter_lints: ^2.0.1
  json_serializable: ^6.3.1

flutter:
  uses-material-design: true

  assets:
    - assets/audio/