name: undervoltage
description: Frontend app for Undervoltage
publish_to: none
version: 0.0.1+1

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  get_it: ^7.6.4
  logger: ^2.0.2+1
  dafluta: ^5.1.1
  just_audio: ^0.9.35
  flutter_tts: ^3.8.3
  url_strategy: ^0.2.0
  json_annotation: ^4.8.1
  web_socket_channel: ^2.4.0
  shared_preferences: ^2.2.2

  firebase_core: ^2.21.0
  firebase_auth: ^4.12.1
  firebase_analytics: ^10.6.3
  firebase_crashlytics: ^3.4.3
  cloud_functions: ^4.5.3
  cloud_firestore: ^4.12.2

  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter 

dev_dependencies:
  lints: ^3.0.0
  dalocale: ^2.4.2
  daassets: ^1.3.2
  daunused: ^1.3.0
  dapublock: ^1.0.1
  build_runner: ^2.4.6
  flutter_lints: ^3.0.1
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true

  assets:
    - assets/audio/
    - assets/images/