name: undervoltage
description: An electrifying game
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  get_it: ^7.2.0
  logger: ^2.0.2+1
  dafluta: ^5.1.1
  share_plus: ^6.0.1
  url_strategy: ^0.2.0
  json_annotation: ^4.6.0
  shared_preferences: ^2.0.15
  
  firebase_core: ^2.16.0
  firebase_auth: ^4.10.0
  firebase_database: ^10.2.6
  firebase_crashlytics: ^3.3.6
  cloud_functions: ^4.4.1

  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter 

dev_dependencies:
  dalocale: ^2.4.2
  daunused: ^1.3.0
  dapublock: ^1.0.1
  build_runner: ^2.2.0
  flutter_lints: ^2.0.1
  json_serializable: ^6.3.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/