name: undervoltage
description: Frontend app for Undervoltage
publish_to: none
version: 0.0.1+1

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  get_it: ^7.6.4
  logger: ^2.0.2+1
  dafluta: ^5.1.1
  flutter_tts: ^3.8.3
  url_strategy: ^0.2.0
  json_annotation: ^4.8.1
  web_socket_channel: ^2.4.0
  shared_preferences: ^2.2.2
  flutter_keyboard_visibility: ^5.4.1

  firebase_core: ^2.20.0
  firebase_auth: ^4.12.0
  firebase_storage: ^11.4.0
  firebase_database: ^10.3.2
  firebase_messaging: ^14.7.2
  firebase_analytics: ^10.6.2
  firebase_crashlytics: ^3.4.2
  firebase_remote_config: ^4.3.2
  cloud_functions: ^4.5.2
  cloud_firestore: ^4.12.1

  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter 

dev_dependencies:
  lints: ^3.0.0
  dalocale: ^2.4.2
  daassets: ^1.3.2
  daunused: ^1.3.0
  dapublock: ^1.0.1
  build_runner: ^2.4.6
  flutter_lints: ^3.0.0
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/