name: tensionpath
description: Battle server for Tension Path
publish_to: none
version: 0.0.1+1

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  json_annotation: ^4.8.1

dev_dependencies:
  lints: ^3.0.0
  daunused: ^1.3.0
  dapublock: ^1.0.1
  build_runner: ^2.4.6
  json_serializable: ^6.7.1